### ISSUE TITLE
Any guides on how to install in Debian?

### ISSUE THREAD

**Issue by imthenachoman** [trizen/fbrowse-tray#2]
I'm not sure sure how to install this on Debian running KDE?

**Comment by trizen** [comment]
First, you need to install the dependencies:

* [Gtk3](https://packages.debian.org/buster/libgtk3-perl)
* [File::MimeInfo](https://packages.debian.org/stable/libfile-mimeinfo-perl)

Probably the command is something like this:

```
sudo apt-get install libgtk3-perl libfile-mimeinfo-perl
```

After installing the dependencies, it should be possible to run the script as:

```console
perl fbrowse-tray ~
```

**Comment by imthenachoman** [comment]
Thank you so much. For some reason I had to run with sudo but it works.
